

<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$link = mysqli_connect("127.0.0.1", "root", "vertrigo", 'mkradius');

if (!$link) {
    die("Falha na conexão: " . mysqli_connect_error());
}


eval(base64_decode('JHF1ZXJ5X3Byb3ZlZG9yID0gbXlzcWxpX3F1ZXJ5KCRsaW5rLCAiU0VMRUNUIGFkZG9uX2JhbmNvLCBhZGRvbl9zZW5oYSBGUk9NIHNpc19wcm92ZWRvciBMSU1JVCAxIik7CgpmdW5jdGlvbiBibG9xdWVhckFkZG9uKCkgewogICAgZWNobyAnPCFET0NUWVBFIGh0bWw+CiAgICA8aHRtbCBsYW5nPSJwdC1iciI+CiAgICA8aGVhZD4KICAgICAgICA8bWV0YSBjaGFyc2V0PSJ1dGYtOCI+CiAgICAgICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xIj4KICAgICAgICA8dGl0bGU+TGljZW7Dp2EgbmVjZXNzw6FyaWE8L3RpdGxlPgogICAgICAgIDxzdHlsZT4KICAgICAgICAgICAgYm9keSB7CiAgICAgICAgICAgICAgICBmb250LWZhbWlseTogQXJpYWwsIHNhbnMtc2VyaWY7CiAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZjlmOWY5OwogICAgICAgICAgICAgICAgbWFyZ2luOiAwOwogICAgICAgICAgICAgICAgcGFkZGluZzogNDBweCAyMHB4OwogICAgICAgICAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyOwogICAgICAgICAgICB9CiAgICAgICAgICAgIC5jb250YWluZXIgewogICAgICAgICAgICAgICAgYmFja2dyb3VuZDogI2ZmZjsKICAgICAgICAgICAgICAgIG1heC13aWR0aDogNDAwcHg7CiAgICAgICAgICAgICAgICBtYXJnaW46IGF1dG87CiAgICAgICAgICAgICAgICBwYWRkaW5nOiAzMHB4OwogICAgICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogMTBweDsKICAgICAgICAgICAgICAgIGJveC1zaGFkb3c6IDAgMCAxMHB4IHJnYmEoMCwwLDAsMC4xKTsKICAgICAgICAgICAgfQogICAgICAgICAgICBoMiB7CiAgICAgICAgICAgICAgICBjb2xvcjogIzMzMzsKICAgICAgICAgICAgfQogICAgICAgICAgICBwIHsKICAgICAgICAgICAgICAgIGZvbnQtc2l6ZTogMTZweDsKICAgICAgICAgICAgICAgIGNvbG9yOiAjNTU1OwogICAgICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMjBweDsKICAgICAgICAgICAgfQogICAgICAgICAgICAuemFwLWJ0biB7CiAgICAgICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7CiAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMjVEMzY2OwogICAgICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICAgICAgcGFkZGluZzogMTVweCAyNXB4OwogICAgICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogOHB4OwogICAgICAgICAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBub25lOwogICAgICAgICAgICAgICAgZm9udC1zaXplOiAxNnB4OwogICAgICAgICAgICAgICAgZm9udC13ZWlnaHQ6IGJvbGQ7CiAgICAgICAgICAgICAgICB0cmFuc2l0aW9uOiBiYWNrZ3JvdW5kIDAuM3MgZWFzZTsKICAgICAgICAgICAgfQogICAgICAgICAgICAuemFwLWJ0bjpob3ZlciB7CiAgICAgICAgICAgICAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjMWViZTVkOwogICAgICAgICAgICB9CiAgICAgICAgICAgIC5udW1iZXIgewogICAgICAgICAgICAgICAgZm9udC1zaXplOiAxOHB4OwogICAgICAgICAgICAgICAgZm9udC13ZWlnaHQ6IGJvbGQ7CiAgICAgICAgICAgICAgICBtYXJnaW4tYm90dG9tOiAxMHB4OwogICAgICAgICAgICAgICAgY29sb3I6ICMxMTE7CiAgICAgICAgICAgIH0KICAgICAgICA8L3N0eWxlPgogICAgPC9oZWFkPgogICAgPGJvZHk+CiAgICAgICAgPGRpdiBjbGFzcz0iY29udGFpbmVyIj4KICAgICAgICAgICAgPGgyPkFkZG9uIG7Do28gbGljZW5jaWFkbzwvaDI+CiAgICAgICAgICAgIDxwPkVudHJlIGVtIGNvbnRhdG8gY29tIDxzdHJvbmc+RWx0b24gUGVyZWlyYTwvc3Ryb25nPiBwYXJhIGF0aXZhw6fDo28gZG8gc2lzdGVtYS48L3A+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im51bWJlciI+8J+TniAoODIpIDk4NzM2LTE5NDM8L2Rpdj4KICAgICAgICAgICAgPGEgY2xhc3M9InphcC1idG4iIGhyZWY9Imh0dHBzOi8vd2EubWUvNTU4Mjk4NzM2MTk0MyIgdGFyZ2V0PSJfYmxhbmsiPkNsaXF1ZSBhcXVpIHBhcmEgZW50cmFyIGVtIGNvbnRhdG8gdmlhIFdoYXRzQXBwPC9hPgogICAgICAgIDwvZGl2PgogICAgPC9ib2R5PgogICAgPC9odG1sPic7CiAgICBleGl0Owp9CgppZiAoISRxdWVyeV9wcm92ZWRvciB8fCAhJHJvdyA9IG15c3FsaV9mZXRjaF9hc3NvYygkcXVlcnlfcHJvdmVkb3IpKSB7CiAgICBibG9xdWVhckFkZG9uKCk7Cn0KCiRhZGRvbl9iYW5jbyA9IHRyaW0oJHJvd1snYWRkb25fYmFuY28nXSk7CiRhZGRvbl9zZW5oYSA9IHRyaW0oJHJvd1snYWRkb25fc2VuaGEnXSk7CgppZiAoJGFkZG9uX2JhbmNvICE9PSAnbWtyYWRpdXMnIHx8ICRhZGRvbl9zZW5oYSAhPT0gJ3ZlcnRyaWdvJykgewogICAgYmxvcXVlYXJBZGRvbigpOwp9Cg=='));

$usuario_logado = isset($_SESSION['MKA_Usuario']) ? $_SESSION['MKA_Usuario'] : (isset($_SESSION['MM_Usuario']) ? $_SESSION['MM_Usuario'] : null);

$permissao = "perm_relFat";

if ($usuario_logado) {
    $query_permissao = mysqli_query($link, "SELECT usuario FROM sis_perm WHERE nome = '$permissao' AND usuario = '$usuario_logado' AND permissao = 'sim'");

    if ($query_permissao) {
        $liberar_permissao = mysqli_num_rows($query_permissao);
        $acesso_permitido = $liberar_permissao >= 1;
    } else {
        echo "Erro na consulta de permissão: " . mysqli_error($link);
        $acesso_permitido = false;
    }
} else {
    $acesso_permitido = false;
}

$ext_mk = (file_exists("../../index.hhvm")) ? '.hhvm' : '.php';
?>

